# Exercícios

## 1) Crie uma classe que irá modelar características geométricas de um círculo. Deverá implementar os métodos:
        -> Área 
        -> Perímetro
## Utilize atributos de classe e de instância apropriados. Crie um inicializador e métodos.
$area = \pi*r^2$

$perimetro = 2*\pi*r$

In [47]:
# resposta 1
class Circle:
    
    def __init__(self, raio):
        import math
        self.pi = math.pi
        self.raio=raio
    
    def area(self):
        return self.pi * self.raio**2
    
    def perimetro(self):
        return 2 * self.pi * self.raio

# Uso
r = int(input('Circulo de raio : '))
circulo = Circle(r)
a = circulo.area()
p = circulo.perimetro()
print('  Raio => %d \n  Perimetro => %d ' % (a,p))

  Raio => 3 
  Perimetro => 6 


## 2) Crie uma classe chamada matemática que conterá duas classes: trigonométrica e algébrica. Defina dentro da classe trigonométrica as seguintes funções:
    -> seno
    -> cosseno
    -> tangente
## Defina dentro da classe algébrica as seguintes funções: 
    -> soma
    -> subtração
    -> multiplicação
    -> divisão
## Cada função deverá receber array e retornar array

In [54]:
# resposta 2
import math
import numpy as np

class Matematica:
    
    class Trigonometrica:

        def __init__(self,arr):
            self.arr = arr

        def seno(self):
            return np.sin(self.arr)

        def cosseno(self):
            return np.cos(self.arr)

        def tangente(self):
            return np.tan(self.arr)

    class Algebrica:

        def __init__(self,arr1,arr2):
            self.arr1 = arr1
            self.arr2 = arr2

        def soma(self):
            return self.arr1 + self.arr2
        
        def subtracao(self):
            return self.arr1 - self.arr2
        
        def multiplicacao(self):
            return self.arr1 * self.arr2
        
        def divisao(self):
            return self.arr1 / self.arr2

#Uso Matematica
#Funções Trigonométricas
print('Funções Trigonométricas')
a = np.array([0, math.pi/2, math.pi, math.pi*(3/2), math.pi*2])
print('Array: %a' % [round(x,2) for x in a])
trig = Matematica.Trigonometrica(a)
print('Sen: %a' % [round(x,2) for x in trig.seno()])
print('Cos: %a' % [round(x,2) for x in trig.cosseno()])
print('Tan: %a' % [round(x,2) for x in trig.tangente()])

#Funções Algébricas
print('Funções Algégricas')
a1 = np.arange(1,11)
a2 = np.arange(10,101,10)
print('Array 1: %a' % a1)
print('Array 2: %a' % a2)
alg = Matematica.Algebrica(a1, a2)
print('Soma: %a' % alg.soma())
print('Subt: %a' % alg.subtracao())
print('Mult: %a' % alg.multiplicacao())
print('Divi: %a' % alg.divisao())

Funções Trigonométricas
Array: [0.0, 1.57, 3.14, 4.71, 6.28]
Sen: [0.0, 1.0, 0.0, -1.0, -0.0]
Cos: [1.0, 0.0, -1.0, -0.0, 1.0]
Tan: [0.0, 1.6331239353195368e+16, -0.0, 5443746451065123.0, -0.0]
Funções Algégricas
Array 1: array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Array 2: array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
Soma: array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110])
Subt: array([ -9, -18, -27, -36, -45, -54, -63, -72, -81, -90])
Mult: array([  10,   40,   90,  160,  250,  360,  490,  640,  810, 1000])
Divi: array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])


## 3) Dados 2 arrays, A e B, remova de A todo elemento pertencente a B

In [50]:
# resposta 3
a = np.random.randint(1,10,size=[4,3])
b = np.random.randint(1,4,size=[3,4])
print(a)
print(b)
r = np.setdiff1d(a,b)
print(r)

[[9 6 7]
 [8 8 8]
 [5 1 4]
 [6 7 3]]
[[3 1 1 3]
 [1 1 1 2]
 [3 1 3 1]]
[4 5 6 7 8 9]


## 4) Crie uma função que recebe um array, um inteiro n e um inteiro m e que retorne outro array contendo elementos que estão entre n e m do array recebido pela função

In [51]:
# resposta 4
def resposta4(r, n, m):
    return r[(r > n) & (r < m)].copy()

#Uso
v = np.array([1,3,5,8,0,6,14])
print(v)
print(resposta4(v, 2, 8))

[ 1  3  5  8  0  6 14]
[3 5 6]


## 5) Escreva uma função que recebe um vetor e um inteiro. Compare cada elemento desse vetor com o número inteiro. Se o elemento do vetor for maior, retorne a diferença entre eles, caso contrário, retorne a soma.

In [52]:
# resposta 5
def resposta5(v, i):
    return np.where(v > i, v-i, v+i)

#Uso
v = np.array([1,3,5,8,0,6])
print(v)
i = int(input('Digite um número inteiro: '))
print(resposta5(v,i))

[1 3 5 8 0 6]
[3 1 3 6 2 4]


## 6) Dada a seguinte matriz:
    -> [ 8,1,7
         4,3,9
         5,2,6]
## escreva uma função que retorne a matriz ordenada por um dos eixos. utilize a função built-in sorted para realizar a ordenação

In [53]:
# resposta 6
import numpy as np
mo = np.array([[8, 1, 7 ], [ 4, 3, 9 ], [5, 2, 6]])

print('Matriz Original')
print(mo)
# Matriz ordenada pelo Axis 1
m = mo.copy()
print('Matriz ordenada pelo Axis 0')
print(np.apply_along_axis(np.sort ,0 ,m))

# Matriz ordenada pelo Axis 0
m = mo.copy()
print('Matriz ordenada pelo Axis 1')
print(np.apply_along_axis(np.sort ,1 ,m))

Matriz Original
[[8 1 7]
 [4 3 9]
 [5 2 6]]
Matriz ordenada pelo Axis 0
[[4 1 6]
 [5 2 7]
 [8 3 9]]
Matriz ordenada pelo Axis 1
[[1 7 8]
 [3 4 9]
 [2 5 6]]
