# Orientação à Objetos

## Classes

In [4]:
#Abstração
class SomeClass:    
    def create_arr(self):
        self.arr = []
    
    def insert_to_arr(self, value): 
        self.arr.append(value)

In [5]:
# Instanciamento
obj = SomeClass()
obj.create_arr()
obj.insert_to_arr(5)
obj.arr

[5]

## Herança Simples

In [7]:
class Pendrive(object):
    def __init__(self, tamanho, interface='2.0'):
        self.tamanho = tamanho
        self.interface = interface
class MP3Player(Pendrive):
    def __init__(self, tamanho, turner=False):
        self.turner = turner
        #Pendrive.__init__(self, tamanho, interface)
        super().__init__(tamanho)
mp3 = MP3Player(1024)
print ('%s\n%s\n%s' % (mp3.tamanho, mp3.interface, mp3.turner))

1024
2.0
False


## Herança Múltipla

In [8]:
class Animal:
    def __init__(self, nomeAnimal):
        print(nomeAnimal, 'é um animal.')

class Mamifero(Animal):
    def __init__(self, nomeMamifero):
        print(nomeMamifero, 'é um animal de sangue quente.')
        super().__init__(nomeMamifero)
    
class MamiferoNaoVoa(Mamifero):
    def __init__(self, nomeMamiferoNaoVoa):
        print(nomeMamiferoNaoVoa, "não pode voar.")
        super().__init__(nomeMamiferoNaoVoa)

class MamiferoNaoMarinho(Mamifero):
    def __init__(self, nomeMamiferoNaoMarinho):
        print(nomeMamiferoNaoMarinho, "não pode nadar.")
        super().__init__(nomeMamiferoNaoMarinho)

class Dog(MamiferoNaoMarinho, MamiferoNaoVoa):
    def __init__(self):
        print('Cachorro tem 4 patas.')
        super().__init__('Cachorro')
    
d = Dog()
print('')
bat = MamiferoNaoMarinho('Morcego') 

Cachorro tem 4 patas.
Cachorro não pode nadar.
Cachorro não pode voar.
Cachorro é um animal de sangue quente.
Cachorro é um animal.

Morcego não pode nadar.
Morcego é um animal de sangue quente.
Morcego é um animal.


In [9]:
Dog.__mro__

(__main__.Dog,
 __main__.MamiferoNaoMarinho,
 __main__.MamiferoNaoVoa,
 __main__.Mamifero,
 __main__.Animal,
 object)

# Numpy

In [14]:
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d)
print(arr1d + 2)
print(type(arr1d))
print(type(list1))
print(list1 + 2)  # erro

[0 1 2 3 4]
[2 3 4 5 6]
<class 'numpy.ndarray'>
<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [15]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

--------- lists ----------

<class 'list'>
[1, 2, 3, 4.5, 5.7]
<class 'int'>
<class 'float'>


--------- array ----------

<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.7]
<class 'numpy.float64'>
<class 'numpy.float64'>


## ndarray

In [16]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
print(arr1.shape)
print(arr1.dtype)

(5,)
float64


In [18]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print(arr2.size)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int64
8


In [43]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print(data4)
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[6.  7.5]
 [8.  1. ]]


In [44]:
data6 = np.arange(15)
print(data6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [45]:
data7 = np.eye(5)
print(data7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [47]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64
float64


In [48]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [53]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Operações entre arrays e escalares

In [54]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [55]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Escalar dividindo array: \n',1/arr3)
print('Array elevado ao quadrado: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
Array elevado ao quadrado: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Fatiamento

In [61]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [62]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[12 12 12]
[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [63]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2]) #igual a print(arr2d[0, 2])

[7 8 9]
3


In [64]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

[[2 3]
 [5 6]]
[4 5]
[[1]
 [4]
 [7]]


## Transposição

In [65]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Flattening

In [74]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
b2 = arr2d.ravel() 
b2[0] = 101
print(arr2d)

----- flatten() -----

[101   2   3   4   5   6   7   8   9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]] 

----- ravel() -----

[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


## Funções Universais

In [67]:
arr = np.arange(10)
print(arr)
np.sqrt(arr) #raiz quadrada
np.exp(arr) #e^x

[0 1 2 3 4 5 6 7 8 9]


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## Localização baseada em Condição e Métodos Estatísticos

In [76]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [77]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [78]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [79]:
arr = np.random.randn(4, 4)
print(arr)
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

[[-0.52264054 -2.19309195 -1.0455171   0.04785103]
 [ 1.56421983 -1.15429187 -0.61857552 -1.27522862]
 [ 0.10619258 -0.44357388  2.39994695 -0.47211136]
 [ 2.36255898 -1.46956094  0.20362531 -1.70206484]]
[[-2 -2 -2  2]
 [ 2 -2 -2 -2]
 [ 2 -2  2 -2]
 [ 2 -2  2 -2]]
[[-0.52264054 -2.19309195 -1.0455171   2.        ]
 [ 2.         -1.15429187 -0.61857552 -1.27522862]
 [ 2.         -0.44357388  2.         -0.47211136]
 [ 2.         -1.46956094  2.         -1.70206484]]


In [82]:
arr = np.random.randn(5, 4)
arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.mean()) #ou np.mean(arr)
print(arr.sum())
print(arr.mean(axis=1))
print(arr.sum(0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
7.0
105
[ 2.  7. 12.]
[15 18 21 24 27]


## Álgebra Linear

In [83]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
[[ 28.  64.]
 [ 67. 181.]]


In [ ]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print(mat)
print(inv(mat)) #inversa

## Geração de Números Aleatórios

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

## Vectorize

In [92]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 returna ', modulo(10))
print('x = 11 returna ', modulo(11))
#print('x = [10, 11, 12] returna ', modulo([10, 11, 12])) # Erro

x = 10 returna  5.0
x = 11 returna  121


In [85]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] returna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] returna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] returna  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] returna  [[  5. 121.   6.]
 [  1.   1.   9.]]


## Aplicar uma função – coluna ou linha

In [86]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [87]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Por linha:  [8 8 6 8]
Por coluna:  [7 8 2 7 6 5 8 5 5 5]


## Outros Métodos

In [88]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

True
False


In [89]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place
print(arr)

[-0.46402358 -0.05702664  0.27592974  1.49451522  0.56682064 -2.30337426
  1.37700072 -1.18738682]
[-2.30337426 -1.18738682 -0.46402358 -0.05702664  0.27592974  0.56682064
  1.37700072  1.49451522]


In [90]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [91]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])